🔀 :: (#14) - 테마 변경 switch component 추가
Team-Ampersand/DUS pull request #16
Opened 2023-04-12 08:32 UTC by ImGaram

# 구현 내용
스위치 버튼 만들기

# 구현 결과
![image](https://user-images.githubusercontent.com/84944117/231399771-eab60011-b657-4922-8834-0298978b9825.png)
![image](https://user-images.githubusercontent.com/84944117/231399825-4ab5ca91-5562-44e5-bad5-bdd32d448056.png)

2023-04-12 08:46 UTC, leehyeonbin commented on app/src/main/java/com/dotori/dus/MainActivity.kt
> +                        Log.d("TAG", "onCreate clicked")
??????

2023-04-12 08:46 UTC, leehyeonbin commented on app/src/main/java/com/dotori/dus/MainActivity.kt
> +                        Log.d("TAG", "onCreate clicked")
이거 혹시 필요한가?

2023-04-12 08:46 UTC, ImGaram commented on app/src/main/java/com/dotori/dus/MainActivity.kt
> +                        Log.d("TAG", "onCreate clicked")
테스트용으로 넣은 거였습니다 지울게요

2023-04-12 08:49 UTC, Cjsghkd commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +    isChecked: Boolean,
그냥 바로 여기서 false로 초기값 넣는것도 나쁘지 않을거 같은데..?

2023-04-12 08:56 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +    buttonHeight: Dp,
이거 근데 컴포넌트가 정해져잇는데 패딩이랑 Width Height왜 받아서해?

2023-04-12 08:56 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +fun DotoriThemeSwitchButton(
위치잡으려면 차라리 
```kotlin
fun DotoriThemeSwitchButton(
    modify: Modify = Modify
) {
    box modify
}
```
이런식으로 정리하는게 사용할 때 더 편할 것 같은데?

2023-04-12 08:56 UTC, baekteun commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +    onSwitchClick: () -> Unit
보통 바뀐값 파라미터로 보내서 (Bool) -> Unit 으로 하지 않음?

2023-04-12 08:59 UTC, baekteun commented on app/src/main/java/com/dotori/dus/MainActivity.kt
> +            Column(
머에여 이 애매한 2줄바꿈

2023-04-12 09:00 UTC, leehyeonbin commented on app/src/main/java/com/dotori/dus/MainActivity.kt
> +            Column(
개빡치네

2023-04-12 09:01 UTC, ImGaram commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +    onSwitchClick: () -> Unit
어느 부분을 말씀하지는 것인지 알 수 있을까요?

2023-04-12 09:03 UTC, leehyeonbin requested changes

2023-04-12 09:03 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +    padding = if (switchClicked) buttonWidth-switchSize-switchPadding*2 else 0.dp
이게 무슨 의도로 사용한지 모르겠는데?

2023-04-12 09:05 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +                    .clip(CircleShape)
이거 사용됨?

2023-04-12 09:08 UTC, ImGaram commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +                    .clip(CircleShape)
CircleShape를 말하는거면 안사용해도 될 것 같네요. 수정하겠습니다.

2023-04-12 09:08 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
> +    Icon(painter = painterResource(id = R.drawable.dark_icon),
이렇게 여러개 들어가는 경우에는 아래로 줄 바꿈 해주는 편이 좋을 것 같아

2023-04-12 09:11 UTC, ImGaram commented on dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
> +    Icon(painter = painterResource(id = R.drawable.dark_icon),
수정했어

2023-04-12 09:11 UTC, ImGaram commented on app/src/main/java/com/dotori/dus/MainActivity.kt
> +            Column(
수정하겠습니다.

2023-04-12 09:12 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
> +    Icon(painter = painterResource(id = R.drawable.dark_icon),
?? 어딜??

2023-04-12 09:13 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
> +    Icon(painter = painterResource(id = R.drawable.dark_icon),
혹시 커밋만하고 푸시 안한거야?

2023-04-12 09:13 UTC, ImGaram commented on dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
> +    Icon(painter = painterResource(id = R.drawable.dark_icon),
아직 커밋을 안했는데 수정했습니다.

2023-04-12 09:14 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
> +    Icon(painter = painterResource(id = R.drawable.dark_icon),
아닠ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 어쩌라는거야 도대체 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 커밋이랑 푸시를 해야 다시 확인하지

2023-04-12 09:21 UTC, ImGaram commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +    padding = if (switchClicked) buttonWidth-switchSize-switchPadding*2 else 0.dp
padding이
![image](https://user-images.githubusercontent.com/84944117/231413272-9c393729-50df-4174-a214-7785955f89bd.png)
에서 스위치를 얼마만큼 움직일건지 설정해주는 역할임

2023-04-12 09:21 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +            easing = LinearOutSlowInEasing
여기도 실행됨?

2023-04-12 09:21 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +            .clip(CircleShape)
여기도 실행 가능해? 이거 Class야 object야?

2023-04-12 09:26 UTC, ImGaram commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +            easing = LinearOutSlowInEasing
tween이 애니메이션을 설정하는 곳임

2023-04-12 10:41 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +            easing = LinearOutSlowInEasing
내 말은 LinearOutSlowInEasing이 뭐 object야?

2023-04-12 10:42 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +    padding = if (switchClicked) buttonWidth-switchSize-switchPadding*2 else 0.dp
아니 저걸 굳이 padding으로 저렇게 계산을 해야해?

2023-04-12 10:45 UTC, leehyeonbin commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +    padding = if (switchClicked) buttonWidth-switchSize-switchPadding*2 else 0.dp
혹시 오프셋이나 패딩을 이미 줬으니까 부모뷰를 기준으로 옮길 수도 있었을텐데 굳이 패딩으로 한 이유가 있냐는 말이지?

2023-04-13 07:59 UTC, Cjsghkd approved these changes

2023-05-28 07:04 UTC, ImGaram commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +    buttonHeight: Dp,
수정했습니당
https://github.com/Team-Ampersand/DUS/pull/16/commits/686f40c0c0e2220a75ecd3035e2cf65664142ffc

2023-07-19 05:27 UTC, ImGaram commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +fun DotoriThemeSwitchButton(
이전 커밋에서 수정 완료
https://github.com/Team-Ampersand/DUS/pull/16/commits/a0d77b78ba3c9bfa283e559ecd35c014e3d44b68

2023-07-19 05:27 UTC, ImGaram commented on dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
> +    onSwitchClick: () -> Unit
이전 커밋에서 수정 완료
https://github.com/Team-Ampersand/DUS/pull/16/commits/a0d77b78ba3c9bfa283e559ecd35c014e3d44b68

2023-07-19 05:36 UTC, closed without merging